language: objective-c
osx_image: xcode7.3
addons:
  artifacts: true

before_script: - carthage bootstrap

script:
- xcodebuild clean build -project AVSExample.xcodeproj

after_success: ./update-gh-pages.sh
